### ISSUE TITLE
Add unit test to improve code coverage

### ISSUE THREAD

**Issue by corinnekrych** [fabric8-ui/fabric8-ui#1238]
Test in isolation:
- services,
- components/directives,
- modules

Let's sub-task the uni tests per module (ie: functionalities of fabric8-ui):
- [ ] unit test for [space-wizard module](https://github.com/fabric8io/fabric8-ui/issues/1545)
- [ ] unit test for settings-wizard module
- [ ] unit test for profile module
- [ ] unit test for shared module
- [ ] unit test for settings module
- [ ] unit test for dashboard module
- [ ] unit test for about-modal module 
- [ ] unit test for landing-page / home / getting started / header / footer

**Comment by corinnekrych** [comment]
Let's sub-task the uni tests per module (ie: functionalities of fabric8-ui):
- [ ] unit test for space-wizard module
- [ ] unit test for space-wizard module
- [ ] unit test for profile module
- [ ] unit test for shared module
- [ ] unit test for settings module
- [ ] unit test for dashboard module
- [ ] unit test for about-modal module 
- [ ] unit test for landing-page / home / getting started / header / footer

**Comment by joshuawilson** [comment]
Cleaned up the and moved the listed to the main description so that it would be easier to track.

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#923
